# Generated by Django 5.1.4 on 2024-12-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_option',
            new_name='answer',
        ),
    ]
